[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/flux"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/rain-onboarding"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/coins-onboarding"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/coins-learning-strategy"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
    
[[headers]]
  for = "/coins-lms"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
